### ISSUE TITLE
typo in "Processing Scenarios Tibbles"

### ISSUE THREAD

**Issue by clchand23** [EpiModel/EpiModeling#15]
@AdrienLeGuillou: Under [Calculating cumulative summaries](https://github.com/EpiModel/EpiModeling/wiki/Processing-Scenarios-Tibbles#calculating-cumulative-summaries), I think the second code block should be `glimpse(d_sc_cml)` instead of `glimpse(d_sc_ly)`.

**Comment by AdrienLeGuillou** [comment]
You are right thanks!
