### ISSUE TITLE
Notes from Christina C (Windows)

### ISSUE THREAD

**Issue by clchand23** [EpiModel/EpiModeling#2]
- When logging into HPC, password is not mirrored on screen for privacy. Do your best to type in the temporary password given to you. Then you will be prompted to retype that password and create a new password. 
 
- Use Powershell on Windows computer if you are not able to connect via Rstudio's terminal.

- If there's an issue with connecting, you can check if the network is setup correctly by typing `ping clogin01.sph.emory.edu` in your terminal.

**Comment by clchand23** [comment]
- CTRL+C is a shortcut to reset the command line if you need to
- `cat config` used to see what's inside config file
- `cat > config` allows you to write a new config file
- CTRL+D is used to save the new config file when done
- to edit aliases, can also use `nano ~/.bashrc` to open up file viewer to add aliases. use arrow keys to scroll to the bottom to add aliases. cannot simply click to bottom to edit

**Comment by clchand23** [comment]
To get `.Renviron` file onto HPC, I ran following command. This asked for password, although I set up ssh key and config file for Host sph. Maybe this was done incorrectly

`scp \Users\clchand\.Renviron clchand@clogin01.sph.emory.edu:~/`

**Comment by clchand23** [comment]
`ssh-copy-id` does not exist for Windows. I copied over the .pub file (the public key) to my .ssh folder on the HPC using `scp`

`scp \Users\NETID\.ssh\emory-hpc-key.pub NETID@clogin01.sph.emory.edu:/.ssh/authorized_keys`

**Comment by smjenness** [comment]
I believe all of the primary comments have been updated on the wiki.
