### ISSUE TITLE
Notes from Laura (Windows-related wiki update)

### ISSUE THREAD

**Issue by laurammann** [EpiModel/EpiModeling#7]
Need to update the wiki to include these instructions to general Windows-related wiki updates:

Before loading packages from renv for BigNets script, ensure that you have installed Rtools for your version of R (https://cran.r-project.org/bin/windows/Rtools/), otherwise you will be unable to install compiled packages (those that include C/C++ or other lower-level code in them, and require some extra work to get installed)

**Comment by smjenness** [comment]
Added separate wiki page for this
